use anyhow::{Result, bail};
use std::path::PathBuf;

const HOOK_MARKER: &str = "# acm prepare-commit-msg hook";

const HOOK_SCRIPT: &str = r#"#!/bin/sh
# acm prepare-commit-msg hook
# Auto-generated by acm. Do not edit.

[ "$ACM_SKIP_HOOK" = "1" ] && exit 0

case "$2" in
  message|merge|squash|commit|template)
    exit 0
    ;;
esac

acm --hook "$1"
"#;

fn hook_path() -> Result<PathBuf> {
    let root = crate::git::repo_root()?;
    crate::git::git_path(&root, "hooks/prepare-commit-msg")
}

pub fn install() -> Result<()> {
    let path = hook_path()?;

    if path.exists() {
        let contents = std::fs::read_to_string(&path)?;
        if !contents.contains(HOOK_MARKER) {
            bail!(
                "prepare-commit-msg hook already exists at {}. \
                Remove it manually or back it up before installing acm's hook.",
                path.display()
            );
        }
        // Our hook — overwrite is OK, fall through.
    }

    // Create parent dir if needed.
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(&path, HOOK_SCRIPT)?;

    // Make executable (chmod 755) on Unix.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&path, perms)?;
    }

    eprintln!("installed prepare-commit-msg hook at {}", path.display());
    Ok(())
}

pub fn uninstall() -> Result<()> {
    let path = hook_path()?;

    if !path.exists() {
        eprintln!("no prepare-commit-msg hook found");
        return Ok(());
    }

    let contents = std::fs::read_to_string(&path)?;
    if !contents.contains(HOOK_MARKER) {
        bail!(
            "prepare-commit-msg hook exists but was not installed by acm. \
            Remove it manually if you want."
        );
    }

    std::fs::remove_file(&path)?;
    eprintln!("removed prepare-commit-msg hook");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    use std::sync::Mutex;
    use tempfile::{TempDir, tempdir};

    // Tests that change the process-wide current directory must not run concurrently.
    static CWD_LOCK: Mutex<()> = Mutex::new(());

    /// Create an isolated git repo via `git init -b main`.
    fn init_repo() -> TempDir {
        let dir = tempdir().expect("failed to create temp dir");
        Command::new("git")
            .args(["init", "-b", "main"])
            .current_dir(dir.path())
            .output()
            .expect("git init failed");
        dir
    }

    #[test]
    fn install_creates_hook_file() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        std::env::set_current_dir(dir.path()).unwrap();

        install().expect("install should succeed");

        let hook = dir.path().join(".git/hooks/prepare-commit-msg");
        assert!(hook.exists(), "hook file should exist");

        let contents = std::fs::read_to_string(&hook).unwrap();
        assert!(contents.contains("acm --hook"), "should contain acm --hook");
        assert!(contents.contains(HOOK_MARKER), "should contain marker");
        assert!(
            contents.contains("ACM_SKIP_HOOK"),
            "hook should honor acm's recursion guard"
        );
        assert!(
            contents.contains("case \"$2\""),
            "hook should branch on prepare-commit-msg source"
        );

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&hook).unwrap().permissions().mode();
            assert!(mode & 0o111 != 0, "hook should be executable");
        }
    }

    #[test]
    fn install_fails_if_hook_exists_without_marker() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        std::env::set_current_dir(dir.path()).unwrap();

        let hooks_dir = dir.path().join(".git/hooks");
        std::fs::create_dir_all(&hooks_dir).unwrap();
        std::fs::write(hooks_dir.join("prepare-commit-msg"), "#!/bin/sh\necho hi\n").unwrap();

        let err = install().unwrap_err();
        assert!(
            err.to_string().contains("already exists"),
            "Expected 'already exists', got: {}",
            err
        );
    }

    #[test]
    fn install_overwrites_existing_acm_hook() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        std::env::set_current_dir(dir.path()).unwrap();

        install().expect("first install should succeed");
        install().expect("second install should succeed (overwrite our own hook)");

        let hook = dir.path().join(".git/hooks/prepare-commit-msg");
        let contents = std::fs::read_to_string(&hook).unwrap();
        assert!(contents.contains(HOOK_MARKER));
    }

    #[test]
    fn uninstall_removes_hook() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        std::env::set_current_dir(dir.path()).unwrap();

        install().expect("install should succeed");

        let hook = dir.path().join(".git/hooks/prepare-commit-msg");
        assert!(hook.exists());

        uninstall().expect("uninstall should succeed");
        assert!(!hook.exists(), "hook file should be removed");
    }

    #[test]
    fn uninstall_noop_if_no_hook() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        std::env::set_current_dir(dir.path()).unwrap();

        // Should succeed without error even when no hook exists.
        uninstall().expect("uninstall with no hook should be a no-op");
    }

    #[test]
    fn install_uses_git_path_in_worktree() {
        let _guard = CWD_LOCK.lock().unwrap();
        let dir = init_repo();
        let path = dir.path();
        std::env::set_current_dir(path).unwrap();
        std::fs::write(path.join("README.md"), "# Test\n").unwrap();
        Command::new("git")
            .args(["add", "README.md"])
            .current_dir(path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "init"])
            .current_dir(path)
            .env("GIT_AUTHOR_NAME", "Test User")
            .env("GIT_AUTHOR_EMAIL", "test@example.com")
            .env("GIT_COMMITTER_NAME", "Test User")
            .env("GIT_COMMITTER_EMAIL", "test@example.com")
            .output()
            .unwrap();

        let worktree = tempdir().expect("failed to create worktree parent");
        let worktree_path = worktree.path().join("linked");
        let output = Command::new("git")
            .args([
                "worktree",
                "add",
                "--detach",
                worktree_path.to_str().unwrap(),
                "HEAD",
            ])
            .current_dir(path)
            .output()
            .expect("git worktree add failed");
        assert!(
            output.status.success(),
            "git worktree add failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        std::env::set_current_dir(&worktree_path).unwrap();
        install().expect("install should work inside linked worktree");

        let hook_path = Command::new("git")
            .args(["rev-parse", "--git-path", "hooks/prepare-commit-msg"])
            .current_dir(&worktree_path)
            .output()
            .unwrap();
        let hook_path = String::from_utf8_lossy(&hook_path.stdout)
            .trim()
            .to_string();
        assert!(std::path::Path::new(&hook_path).exists());
    }
}
